### ISSUE TITLE
snapping back to 0,0,0

### ISSUE THREAD

**Issue by yvepilled** [LeonBlade/BDTHPlugin#36] opened 2022-07-15 08:26 UTC
hello! i have recently encountered something i've never dealt with before while using bdth. whenever i hover over the coordinates, they are automatically set at 0 - no clue how this happened. it will not show the coordinates of the item i am placing, and will just show the same 0 X, 0 Y, 0 Z input. whenever i hover over the menu to see coordinates, it snaps back from where i had moved it.
i have attached a video of it below:
[video via discord](https://cdn.discordapp.com/attachments/877924425910075433/997417321297608774/2022-07-15_01-19-20.mp4)

**Comment by antares005** [comment] 2022-07-15 08:40
I was having this issue today, but what worked for me is I went to the Dalamud Plugins, right-clicked BDTH and clicked reset plugin and reload. Hopefully it'll work for you.

**Comment by yvepilled** [comment] 2022-07-15 08:56
> 

this worked for me, thank you ;-;

**Comment by LeonBlade** [comment] 2022-08-02 19:01
I believe the latest version fixes this. I will close this within a week if the issue is fixed.

**Closed** 2022-08-11 01:33 UTC
